### ISSUE TITLE
Crash on align tiling when running RNN GRU models enabling sigmoid

### ISSUE THREAD

**Issue by pfultz2** [ROCm/rocMLIR#1188]
After fixing a missing comma, MLIR will now work with sigmoid operators, but this causes the `./bin/test_verify test_gru_bidirct` test to fail in migraphx on mi100:

```
UNREACHABLE executed at /usr/local/cget/build/tmp-832dcb3bff0f4556884f71aa299c95b7/rocMLIR-1ad9d6df32acc6d29d58e8ed6710e36746d0a4d6/mlir/lib/Dialect/Rock/Transforms/AlignTiling.cpp:98!
```

**Comment by krzysz00** [comment]
Would it be too much trouble to collect a `MIGRAPHX_TRACE_MLIR=1` trace of this?

**Comment by krzysz00** [comment]
Also (even though I'm not hopeful here) does updating to the latest `develop` (which includes https://github.com/ROCmSoftwarePlatform/rocMLIR/pull/1186) fix it?

**Comment by jerryyin** [comment]
This is a duplicate to https://github.com/ROCmSoftwarePlatform/rocMLIR-internal/issues/1098. I'm going to reference this in 1098 in its acceptance criteria.
