### ISSUE TITLE
Some observations from gfx1102 runs

### ISSUE THREAD

**Issue by jungpark-mlir** [ROCm/rocMLIR#1245]
Hi,

I've got a RX7600 card which has gfx1102 with wmma support and here's a couple of issues I found.

I tested a 1k*1k*1k gemm with this,
./bin/rocmlir-gen -ph -operation gemm -t f16 -out_datatype f16 --arch gfx1102 --num_cu 32 -g 1 -m 1024 -k 1024 -n 1024 -transA=True -transB=False

Initially picked tuning params is
```
// -----// IR Dump After RockAffixTuningParametersPass (rock-affix-params) //----- //
func.func @rock_gemm(%arg0: memref<1x1024x1024xf16>, %arg1: memref<1x1024x1024xf16>, %arg2: memref<1x1024x1024xf16>) attributes {block_size = 128 : i32, grid_size = 64 : i32, kernel, mhal.arch = "amdgcn-amd-amdhsa:gfx1102", wave_size = 32 : i32} {
  rock.gemm %arg2 = tr %arg0 * %arg1 features =  dot|atomic_add|atomic_fmax_f32|wmma storeMethod =  set {arch = "amdgcn-amd-amdhsa:gfx1102", derivedBlockSize = 128 : i32, gridSize = 64 : i32, numCU = 32 : i32, params = #rock.wmma_gemm_params<kpackPerBlock = 4, mPerBlock = 128, nPerBlock = 128, kpack = 16, mPerWave = 64, nPerWave = 64, forceUnroll = true>} : memref<1x1024x1024xf16> = memref<1x1024x1024xf16> * memref<1x1024x1024xf16>
  return
}
```
Which is  --perf_config='128, 128, `4`, 64, 64, 16, 1, `1`' 
This runs and verifies with cpu result (when enabled). 
But it looks mismatching with validRangeWmmaGemmParams in tuning, which has `{16, 32}` for kPerBlock and sets `false` to the last param.

The other issue is, it causes gpu hang for lots of tuning params, for example,
```
 --perf_config='16, 32, 16, 16, 32, 16, 1, 0'
 --perf_config='16, 64, 16, 16, 64, 16, 1, 1'
 --perf_config='32, 16, 32, 16, 16, 16, 1, 0'
 --perf_config='32, 32, 32, 16, 32, 16, 1, 0'
 --perf_config='64, 16, 16, 32, 16, 16, 1, 0'
```

What I've noticed is, those failing ones use even larger amount of vgprs and compiler spilled it to memory.
```
    .sgpr_count:     18
    .sgpr_spill_count: 0
    .symbol:         rock_gemm.kd
    .vgpr_count:     256
    .vgpr_spill_count: 22
    .wavefront_size: 32
```
While kernels which can run don't have spilt vgpr. Not sure that's actually causing the issue, just checked several cases.

**Comment by giuseros** [comment]
Hi @jungpark-mlir ! 

I had a first go at this, and I think there are three issues here:
- The last param is not used. It is usually put to `true` and it's probably been a typo introduced [here](https://github.com/ROCmSoftwarePlatform/rocMLIR/commit/32ef0efda6b354f9be92f83220cdb6843138bf9d): 
- I think the `kouter` tuning range is wrong for wmma. We should use the same that the xdlops path uses, but for some reason in [this PR](https://github.com/ROCmSoftwarePlatform/rocMLIR/commit/df9240a24c9441cdb2408a2bab4527c54a9999ea) I set it to 16/32 (it's likely that setting them smaller we might gain even some performance back). When I reduce the value of `kOuter` the spills seem to disappear:
```
 --perf_config='16, 64, 16, 16, 64, 16, 1, 1' ->  .vgpr_spill_count: 600
 --perf_config='16, 64, 8, 16, 64, 16, 1, 1' ->  .vgpr_spill_count: 87
 --perf_config='16, 64, 4, 16, 64, 16, 1, 1' ->  .vgpr_spill_count: 0
```
- However, I was not able to reproduce the hanging issue. All the configurations you gave me ran on a gfx1101 architecture (the spilling ones ran quite slower). 

I can try to understand why increasing the `kOuter` parameter leads to spills, but my immediate solution would be:
- Set the last tuning parameter to `true`
- Use the same xdlops `kOuter` range for wmma

**Comment by giuseros** [comment]
cc @krzysz00

**Comment by jungpark-mlir** [comment]
Thanks for the response @giuseros 

I suppose gfx1102 is relatively newer and the hanging issue is not resolved yet. (I'm using rocm5.6 btw)
Now, I'm able to WA the issue in my script by simply skipping spilt configs as below, 
``` 
             perf_config = str(mb) + ", " + str(nb) + ", " + str(kb) + ", " + str(mw) + ", " + str(nw) + ", " + str(kp) + ", " + str(fu) + ", 1"
             gen_str = config_str + "--perf_config='" + perf_config + "' | ./bin/rocmlir-driver -c --debug-only=serialize-to-blob >./1kx.ir 2>dis.txt"
             print("#" + str(cnt) + ": [" +  perf_config + "]")
             # Gen kernel
             try:
               sp.check_output(gen_str, shell=True, text=True)
             except:
               continue

             # Check vgpr spill, skip if spilt. Potentially hang
             try:
               num_vspill = sp.check_output("gawk '/vgpr_spill/ {print $2}' ./dis.txt", shell=True, text=True)
             except:
               continue
             if int(num_vspill) != 0:
               continue
            
             # Execute the kernel if everything is fine.
             try:
               sp.check_output("/opt/rocm/bin/rocprof --stats ./external/llvm-project/llvm/bin/mlir-cpu-runner -O2 --shared-libs=...
``` 

And that's a good point, I can see `kOuter` param determines the tile sizes of both block and thread. Probably larger tile size per a thread simply requires larger amount of registers, so it's more likely to exceed total available vgprs.
