### ISSUE TITLE
private copy of llvm

### ISSUE THREAD

**Issue by trixirt** [ROCm/rocMLIR#1326]
I am packaging rocMLIR for Fedora

Fedora will have a problem with the local copy of the llvm-project.
The use of [ROCm llvm](https://github.com/RadeonOpenCompute/llvm-project) was rejected, so (likely) will be rocMLIR's.

rocMLIR needs to work with the system's llvm.

**Comment by krzysz00** [comment]
Because rocMLIR is part of the ROCm stack, it will use ROCm components, including (going forward) AMD's branches of LLVM.

If you want rocMLIR to work with system LLVMs or to otherwise work against LLVMs that we don't develop against, you're welcome to put that work in.

**Comment by krzysz00** [comment]
Note additionally that the rocMLIR team maintains patches on top of MLIR.

We have plans in the future to migrate to the comgr library for LLVM invocations, but that's in the future and won't quite solve your problem
