### ISSUE TITLE
rocMLIR installation is failed

### ISSUE THREAD

**Issue by qianqing13579** [ROCm/rocMLIR#1444]
I use following instrutions to install rocMLIR
```
mkdir build
cd build
cmake -G Ninja .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++
ninja check-rocmlir
```
and an error occurred:
```
rocmlir/external/llvm-project/mlir/lib/Dialect/GPU/AmdDeviceLibsIncGen.py: Permission denied
```
I do not know why?

**Comment by krzysz00** [comment]
@qianqing13579 Check if the script mentioned in that error message is executable? You might need to `chmod +x` it, which is weird, since I'm pretty sure it got committed as such - or gets called via `python3` anyway.

**Comment by qianqing13579** [comment]
@krzysz00 ,I use chmod +x, but an error occurred as follows:
```
[1/3559] Generating device libraries include package
FAILED: external/llvm-project/llvm/tools/mlir/lib/Dialect/GPU/Transforms/AmdDeviceLibs.cpp.inc /root/rocmlir/build/external/llvm-project/llvm/tools/mlir/lib/Dialect/GPU/Transforms/AmdDeviceLibs.cpp.inc
cd /root/rocmlir/build/external/llvm-project/llvm/tools/mlir/lib/Dialect/GPU && /root/rocmlir/external/llvm-project/mlir/lib/Dialect/GPU/AmdDeviceLibsIncGen.py /root/rocmlir/build/external/llvm-project/llvm/tools/mlir/lib/Dialect/GPU/Transforms/AmdDeviceLibs.cpp.inc /opt/rocm ocml ockl hip asanrtl
/usr/bin/env: ‘python3\r’: No such file or directory
```

**Comment by krzysz00** [comment]
... huh, that's weird, I'll look into why there's a windows newline in there

**Comment by krzysz00** [comment]
... can you take a look at your git configuration to see if it's adding DOS newlines?

**Comment by rakicaleksandar1999** [comment]
@qianqing13579 Did you try setting the following `cmake` options?
`-DCMAKE_PREFIX_PATH`
`-DCMAKE_INSTALL_PREFIX`
`-DROCM_PATH`
`-DROCM_TEST_CHIPSET`
`-DBUILD_FAT_LIBROCKCOMPILER`

**Comment by krzysz00** [comment]
I don't think those would necessarily be related, I'm suspecting Git auto-crlf issues given the `\r` in the Python executable name

**Comment by qianqing13579** [comment]
@krzysz00 , the problem is solved,thanks
