### ISSUE TITLE
mlir-rocm-runner hipErrorSharedObjectInitFailed during gpu-to-hsaco.mlir

### ISSUE THREAD

**Issue by raikonenfnu** [ROCm/rocMLIR#159]
Hey guys,

I am testing out mlir-rocm-runner with gpu-to-hsaco.mlir but seems to be getting some error when doing createGpuToLLVMConversionPass. 

If I comment out the call to other_func in gpu-to-hsaco.mlir it works fine, but obviously I'd like to do something with the GPUs :). I have attached a screenshot to the error called out. 

This is my cmd line:./mlir-rocm-runner --triple="amdgcn-amd-amdhsa" --target="gfx906" --shared-libs=librocm-runtime-wrappers.so,libmlir_runner_utils.so --entry-point-result=void ../gpu-to-hsaco.mlir

<img width="838" alt="Screen Shot 2021-04-22 at 6 20 44 PM" src="https://user-images.githubusercontent.com/68087699/115804895-c1665e00-a398-11eb-8550-e4f8dcf848a8.png">

Thanks in advance for all your help! A fan of your work 😄 !

**Comment by raikonenfnu** [comment]
SHA I am on: e2e0d6fa9ebd369d5ee5f0c8c57979395a0626c4

**Comment by whchung** [comment]
@raikonenfnu This seems like an installation issue. Could you share what ROCm version you are using? And could you first verify if samples under `/opt/rocm/hip/samples` could build and run properly?

**Comment by whchung** [comment]
BTW your command works fine on my node:

```
~/llvm-project-mlir/build$ ./bin/mlir-rocm-runner --triple="amdgcn-amd-amdhsa" --target="gfx908" --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void ../mlir/test/mlir-rocm-runner/gpu-to-hsaco.mlir
Unranked Memref base@ = 0x55918da9a390 rank = 1 offset = 0 sizes = [5] strides = [1] data =
[-9.39541e-31,  3.06954e-41,  0,  0,  4.48416e-44]
Unranked Memref base@ = 0x55918da9a390 rank = 1 offset = 0 sizes = [5] strides = [1] data =
[1,  1,  1,  1,  1]
```

You may want to determine your GPU target with this command:

```
/opt/rocm/bin/rocm_agent_enumerator -t GPU
```

**Comment by raikonenfnu** [comment]
@whchung, thanks for the suggestions, but still didn't quite get it to work yet.

 just for extra context, I am building on my local machine that has 6900xt (gfx1030 + ROCM4.1.0), but I am running binaries on (gfx906 + ROCM4.1.1) on the server where I am not allowed to build. 

I was able to build some of the /opt/rocm/samples by setting offload_arch="gfx906" on my local(gfx1030) and running it on the server(gfx906). I also did "/opt/rocm/bin/rocm_agent_enumerator -t GPU" to verify that I have the right gpu targets i.e gfx906 and gfx1030. 

Another clue might be the binaries I built on my local wouldn't run locally perhaps ,because 6900xt-ROCM is not quite supported yet? 

Thanks in advance again for your help! 😃

**Comment by whchung** [comment]
The instruction set is different between gfx906 and gfx1030, so it's not possible to run a gfx906 binary on a gfx1030 machine.

In this project we use LLVM in January 2021 which should already have gfx1030 code emission logic, so it's possible to produce gfx1030 binary from this project. But since ROCm doesn't officially support gfx1030 yet, the HIP runtime and its underlying pieces in ROCm 4.1.x won't be able to execute it on your local box.

**Comment by raikonenfnu** [comment]
@whchung That makes sense! But similar to how we can set offload_arch="gfx906" for hipcc to get sample rocm/hip programs working, is there a way we can do that to set the mlir-rocm-runner binary built in gfx1030 work with gfx906?

**Comment by whchung** [comment]
On your gfx906 machine, this should work out of the box:

```
./mlir-rocm-runner --shared-libs=librocm-runtime-wrappers.so,libmlir_runner_utils.so --entry-point-result=void ../gpu-to-hsaco.mlir
```

`mlir-rocm-runner` is not fixated on any particular AMD GCN ISA version. Instead, it would use `/opt/rocm/bin/rocm_agent_enumerator` to understand the ISA version on the system, and use LLVM to JIT the binary, and then use HIP runtime API to launch the produced GPU kernel. So ideally you shouldn't really need to specify `--triple` or `--target`.

On the other hand, on your gfx1030 machine, it wouldn't yet (compiler part should work, but not the runtime part).

**Comment by raikonenfnu** [comment]
I see I see, that makes sense since with and without --triple and --target flag they have the same behaviour. But hip is still throwing out the same errors. 

I was wondering if it could be possible that perhaps the difference in ROCm version might the cause of this errors (ROCm 4.1.1 vs ROCm 4.1.0). I also generated the mlir file right before it goes through the jitrunner. Do you think there's anything perhaps that looks fishy going on here?
[tmp.mlir.zip](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/files/6367102/tmp.mlir.zip)

**Comment by raikonenfnu** [comment]
hmmm is it perhaps not accessing the bin pointer correctly 🤔 :
<img width="1417" alt="Screen Shot 2021-04-23 at 11 28 53 AM" src="https://user-images.githubusercontent.com/68087699/115914763-3bddbf00-a427-11eb-8343-9eb7cab339dd.png">
<img width="750" alt="Screen Shot 2021-04-23 at 11 29 04 AM" src="https://user-images.githubusercontent.com/68087699/115914775-3f714600-a427-11eb-9f41-70c38afde92d.png">

**Comment by whchung** [comment]
@raikonenfnu I don't know the difference between ROCm 4.1.0 and ROCm 4.1.1 that well so I can't say for sure. In case you can use `docker` on your gfx906 machine I recommend you try the commands we employ in our CI scripts under `mlir/utils/jenkins/Jenkinsfile.downstream`. You can see how we pull a docker image, configure the build, and run the tests. Also we just upgraded the scripts to use ROCm 4.1.1 in PR #163 .

**Comment by raikonenfnu** [comment]
@whchung I reinstalled 4.1.1 into my local machine and rebuild everything, but still doesnt work 😅.
I'll test the jenkinfile out and see if that works! Thank you for your help , I'll let you know if it works out 😄

**Comment by whchung** [comment]
@raikonenfnu a gentle ping. Are you still experiencing the issue? I'm closing this issue for now, as our internal CI have all be using ROCm 4.1.1, and we are starting testing against newer ROCm versions. If you still have the issue, please feel free to reopen this ticket. Thanks.

**Comment by raikonenfnu** [comment]
Sorry Jack, yes, this issue is gone, I went through a couple iterations for this. I think key take away for myself is to ensure:
-Compiling to correct gfx architecture
-Check if need to link to Device Library bitcodes and link appropriately

Thanks for the support Jack! Really appreciate it :)
