### ISSUE TITLE
[Issue]: Installation missing cmake 

### ISSUE THREAD

**Issue by trixirt** [ROCm/rocMLIR#1593]
### Problem Description

Trying to use rocMLIR with MIOpen.  MIOpen expects to find rocMLIR with the usual cmake config file
https://github.com/ROCm/MIOpen/blob/develop/CMakeLists.txt#L408

A successful build / install produces a lot of *.so's but no cmake/rocMLIR

### Operating System

Fedora 40

### CPU

x86_64

### GPU

AMD Radeon Pro W7900

### ROCm Version

ROCm 6.1.0

### Steps to Reproduce

mkdir build
cd build

prefix=$PWD/install
launcher=ccache

cmake -G Ninja \
       -DCMAKE_INSTALL_PREFIX=${prefix} \
       -DAMDGPU_TARGETS=gfx1100 \
       -DBUILD_SHARED_LIBS=OFF \
       -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_SKIP_RPATH=ON \
       -DCMAKE_C_COMPILER=gcc \
       -DCMAKE_CXX_COMPILER=g++ \
       -DCMAKE_C_COMPILER_LAUNCHER=$launcher \
       -DCMAKE_CXX_COMPILER_LAUNCHER=$launcher \
       -DLLVM_BUILD_TOOLS=OFF \
       -DLLVM_LIBDIR_SUFFIX=64 \
       -DLLVM_ENABLE_PROJECTS="lld;mlir;llvm" \
       -DLLVM_INCLUDE_DOCS=OFF \
       -DLLVM_INCLUDE_EXAMPLES=OFF \
       -DLLVM_INCLUDE_TESTS=OFF \
       -DLLVM_TARGETS_TO_BUILD="X86;AMDGPU" \
       -DMLIR_INCLUDE_TESTS=OFF \
       .. 

if [ -f build.ninja ]; then
    ninja 
    if [ $? = 0 ]; then
	ninja install
    else
	bash
	exit 1
    fi
fi

$ find install
install
install/lib64
install/lib64/libMLIRRockAnalysis.so.2.0
install/lib64/libMLIRRockAnalysis.so
install/lib64/libRocmlirEmulateFp8ExtTrunc.so.2.0
install/lib64/libRocmlirEmulateFp8ExtTrunc.so
install/lib64/libMLIRGPUToMIGraphX.so.2.0
install/lib64/libMLIRGPUToMIGraphX.so
install/lib64/libMLIRMIGraphXToTosa.so.2.0
install/lib64/libMLIRMIGraphXToTosa.so
install/lib64/libMLIRRockToGPU.so.2.0
install/lib64/libMLIRRockToGPU.so
install/lib64/libMLIRTosaToRock.so.2.0
install/lib64/libMLIRTosaToRock.so
install/lib64/libMLIRRockOps.so.2.0
install/lib64/libMLIRRockOps.so
install/lib64/libMLIRRockTransforms.so.2.0
install/lib64/libMLIRRockTransforms.so
install/lib64/libMLIRRockTuning.so.2.0
install/lib64/libMLIRRockTuning.so
install/lib64/libMLIRRockConv2dGenerator.so.2.0
install/lib64/libMLIRRockConv2dGenerator.so
install/lib64/libMLIRRockPipeline.so.2.0
install/lib64/libMLIRRockPipeline.so
install/lib64/libMLIRRockUtility.so.2.0
install/lib64/libMLIRRockUtility.so
install/lib64/libMLIRMIGraphXDialect.so.2.0
install/lib64/libMLIRMIGraphXDialect.so
install/lib64/libMLIRMIGraphXTransforms.so.2.0
install/lib64/libMLIRMIGraphXTransforms.so
install/lib64/libMLIRMIGraphXPipeline.so.2.0
install/lib64/libMLIRMIGraphXPipeline.so
install/lib64/libconv-validation-wrappers.so.2.0
install/lib64/libconv-validation-wrappers.so
install/lib64/libMLIRRocTarget.so.2.0
install/lib64/libMLIRRocTarget.so
install/lib64/libGpuModuleToRocdlirTranslation.a
install/lib64/libMLIRCAPIMIGraphX.so.2.0
install/lib64/libMLIRCAPIMIGraphX.so
install/lib64/objects-Release
install/lib64/objects-Release/obj.MLIRCAPIMIGraphX
install/lib64/objects-Release/obj.MLIRCAPIMIGraphX/MIGraphX.cpp.o
install/lib64/objects-Release/obj.MLIRCAPIRock
install/lib64/objects-Release/obj.MLIRCAPIRock/Rock.cpp.o
install/lib64/objects-Release/obj.MLIRCAPIRegisterRocMLIR
install/lib64/objects-Release/obj.MLIRCAPIRegisterRocMLIR/RegisterRocMLIR.cpp.o
install/lib64/libMLIRCAPIRock.so.2.0
install/lib64/libMLIRCAPIRock.so
install/lib64/libMLIRCAPIRegisterRocMLIR.so.2.0
install/lib64/libMLIRCAPIRegisterRocMLIR.so
install/lib64/libRocMLIROptMain.a

### Additional Information

with develop branch

**Comment by krzysz00** [comment]
MIOpen is pinned to a really old build of rocMLIR and you'll need to grab something near there, since our projects haven't really been working together since a good while back.

**Comment by trixirt** [comment]
D'oh!
I will look at MIGraphX then.
Thanks
