### ISSUE TITLE
Upstream use of target attributes for compilation 

### ISSUE THREAD

**Issue by umangyadav** [ROCm/rocMLIR#1641]
https://github.com/ROCm/rocMLIR/pull/1548

Commits from these PRs showed up when doing diff with upstream.

Definition of Done (DoD):
Feel free to close this ticket if it is not relevant or it is already upstreamed. Please provide all the info/refs/links on upstream PRs if it is already upstreamed.

**Comment by umangyadav** [comment]
@fabianmcg  Is this something you willing to help since you are the original author ? 

cc : @manupak  @jerryyin @krzysz00

**Comment by fabianmcg** [comment]
All of it is upstream*. However, there are a couple of differences between the dowstream rocMLIR version and upstream MLIR components, namely `KernelAttr` got renamed to `KernelMetadataAttr` and some utilities in `mlir/lib/Target/LLVM/ROCDL/Utils.cpp` got moved to `llvm`.

In normal times I would gladly offer up a patch right away, however, I'm in the process of submitting my thesis manuscript within the next couple of weeks. Thus, I can not make the patch until after the 24th of Sept.

**Comment by krzysz00** [comment]
I'll suggest we close this and merge the changes from upstream during the next merge

**Comment by jerryyin** [comment]
Let's keep this ticket open to track this difference, and close when it is resolved by upstream merge.

**Comment by dhernandez0** [comment]
Resolved by upstream merge.
