### ISSUE TITLE
[Documentation]: Fix rocdl dialect document

### ISSUE THREAD

**Issue by jungpark-mlir** [ROCm/rocMLIR#1654]
### Description of errors

There's documentation, autogen'ed from `mlir/include/mlir/Dialect/LLVMIR/ROCDLOps.td`
https://mlir.llvm.org/docs/Dialects/ROCDLDialect/

It pretends everything is OK but is broken actually.
We have much more operations than it's currently showing.
For example, if you search `sched` on the page, it'll show you the hidden broken part of the page.

DoD : Fix the definition, so we can see all the operations and brief summary.

**Comment by krzysz00** [comment]
Could you file this upstream please? Possibly with a PR?
