### ISSUE TITLE
[Question] Is xdlops_gemm_v2 usable? 

### ISSUE THREAD

**Issue by raikonenfnu** [ROCm/rocMLIR#321]
I have seen examples of xdlops_gemm_v2 mlirs, but I do not see lowerings to LLVMIR or transformation to rocdl's mfma.
example [here](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/80ffee6b1bfbe5bc69d51dc5316be2a1906d96e1/mlir/test/Dialect/MIOpen/lowering_xdlops_gemm_v2.mlir), seems to be using "lowering-step5", which seems to be (affine->std) + (Loop -> std). any guidance would be appreciated :)

**Comment by whchung** [comment]
It's implemented in `miopen-lowering-step4`:

https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/miopen-dialect/mlir/lib/Dialect/MIOpen/Transforms/LowerMIOpenOps.cpp#L157
