### ISSUE TITLE
[Question] What is the purpose of Immediate values/imm in xdlop's mfma?

### ISSUE THREAD

**Issue by raikonenfnu** [ROCm/rocMLIR#337]
As asked in the title what is the purpose of Immediate values/imm in xdlop's mfma? as seen [here](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/80ffee6b1bfbe5bc69d51dc5316be2a1906d96e1/mlir/test/Conversion/GPUToROCDL/gpu-to-rocdl.mlir#L367)

Seems like it can default to [0,0,0] as seen in this gpu lowering pass [here](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/af70757947147c5b13b053ea908861f764630842/mlir/lib/Conversion/GPUToROCDL/LowerGpuOpsToROCDLOps.cpp#L761). Thanks in advance! :)

**Comment by whchung** [comment]
Please refer to:
https://developer.amd.com/wp-content/resources/CDNA1_Shader_ISA_14December2020.pdf

This specifies the BLGP field (Table 82 VOP3P-MAI Fields).

@zjing14 knows the details much better than I do. We have an internal training slide and we can see if it's possible to open source it.

**Comment by raikonenfnu** [comment]
> Please refer to:
> https://developer.amd.com/wp-content/resources/CDNA1_Shader_ISA_14December2020.pdf
> 
> This specifies the BLGP field (Table 82 VOP3P-MAI Fields).
> 
> @zjing14 knows the details much better than I do. We have an internal training slide and we can see if it's possible to open source it.

That'd be awesome @whchung! Thanks :)
