### ISSUE TITLE
[Question] Are there any docs on usage of MiOpen dialect gemm with xdlops

### ISSUE THREAD

**Issue by raikonenfnu** [ROCm/rocMLIR#340]
Hey guys, I have a question, I am trying to set up a toy example of gemm using xdlops with the miopen dialect. I have seen the example [miopen_xdlops_gemm_v2_one_result_f16](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/d0bc2c956231415039e51da3a0ac6f3d398f8b4a/mlir/test/Dialect/MIOpen/ops_blockwise_f16.mlir#L38) but it does not seem very obvious to me how the function signature works. 

Looking at the [op definition](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/d0bc2c956231415039e51da3a0ac6f3d398f8b4a/mlir/include/mlir/Dialect/MIOpen/MIOpenOps.td), and lowering to [MFMA](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/af70757947147c5b13b053ea908861f764630842/mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h#L8825), I can slightly understand that matrixA and matirxB is supposed to be the initial matrix which we load into bufferA and bufferB for computation, and the two indices are wave offsets.

But I still don't quite  understand why matrixA and matrix B has a size of 12288xf16. I was wondering if there exist docs on this and if you have any pointer on writing simple gemm test cases for miopen dialect with xdlops. Thanks in advance! :)

**Comment by whchung** [comment]
There is no public documentation available wrt how MIOpen dialect works.

The implementation of MIOpen dialect, is derived from MIOpen C++ implementation, which is publicly available at: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp

I would recommend you raise the question over MIOpen repository, and also contact @zjing14 who is the expert in this field.

**Comment by raikonenfnu** [comment]
Thanks for all the help and guidance @whchung!
