### ISSUE TITLE
[bf16]debug build verification failed

### ISSUE THREAD

**Issue by asleepzzz** [ROCm/rocMLIR#49]
bf16 PR:
https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/pull/45

release build pass, but debug build failed

./bin/mlir-miopen-driver -p=false  -c -x2 -t bf16 fil_layout=kcyx -in_layout=nchw -out_layout=nkhw  -batchsize=64 -in_channels=4 -out_channels=64 -in_h=32 -in_w=32 -fil_h=3 -fil_w=3  --dilation_h=1 --dilation_w=1 --padding_h=0 --padding_w=0 --conv_stride_h=2 --conv_stride_w=2 -pv  | ./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void

release build:
gpu results:32.0   cpu:32.0

debug build:
gpu results:32.02   cpu:32.12

create this issue to track , will look into ISA

**Comment by whchung** [comment]
this ticket is no longer valid. close it hereby.
