### ISSUE TITLE
[MLIR] How to target MFMA ops for AMDGPU backend?

### ISSUE THREAD

**Issue by nirvedhmeshram** [ROCm/rocMLIR#643]
I see these ops in the repository
https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/0ed808679fbaf19b0379f76ea2e1d3c95ac3fe88/external/llvm-project/mlir/include/mlir/Dialect/GPU/GPUOps.td#L1265
However, I dont see them available upstream. Is there currently some way to target MFMA ops for AMDGPU backend in upstream MLIR?

**Comment by whchung** [comment]
+ @krzysz00 / @jerryyin .

@nirvedhmeshram , we are in the process of removing AMDGPU-specific ops from GPU dialect, and move them to `amdgpu` / `rocdl` dialect. We'll upstream all the changes.

**Comment by krzysz00** [comment]
Yeah, once I get https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/pull/628 merged here, I'll send it upstream

**Comment by nirvedhmeshram** [comment]
Thank you!
