### ISSUE TITLE
Blockwisegemm Summary

### ISSUE THREAD

**Issue by jerryyin** [ROCm/rocMLIR#719]
### Signature of Blockwisegemm Op

```tablegen
Arguments<(ins MemRefRankOf<[F32, F16, BF16, I8], [3]>:$matrixA,
               MemRefRankOf<[F32, F16, BF16, I8], [3]>:$matrixB,
               MemRefRankOf<[F32, F16, BF16, I32], [2]>:$matrixC,
               IndexAttr:$kPerThread,
               IndexAttr:$mPerThread,
               IndexAttr:$nPerThread,
               IndexAttr:$mThreadsPerCuwave,
               IndexAttr:$nThreadsPerCuwave,
               IndexAttr:$mCuwavesPerBlock,
               IndexAttr:$nCuwavesPerBlock
               )> {
```

The `miopen.blockwise_gemm` op does gemm at the blockwise level without xdlops. 
  - Matrix A resides in LDS and has dimensions [k, M_b , kPack].
  - Matrix B resides in LDS and has dimensions [k, N_b, kPack].
  - Matrix C resides in registers and has dimensions [m_c, n_c], where m_c = mRepeat * mPerThread and n_c = nRepeat * nPerThread.
  - It is the case that m_a = m_c * mCuwaves * mThreadsPerCuwave and n_a = n_c * nCuwaves * nThreadsPerCuwave
  - m/n/k per thread: Tuning parameter showing the length of the smallest-level tiles in the m/n/k dimension that will be passed to the threadwise gemm, which computes over m/n Repeat of such tiles.
  - m/n threads per cu wave: Both currently hard-coded as 4
  - m/n cu waves per block: Number of cu waves in a block

### Divisions of the work in a block

Simplified representations:
 - mCuwavesPerBlock and nCuwavesPerBlock are simplified as M and N
 - mThreadsPerCuwave and nThreadsPerCuwave are simplified as m and n
 - With above, number of threads per cu wave is `threads = m * n = 16`
 - Tile size satisfy: 
   - `MPerBlock = MRepeat * (M * m * MPerThread)`
   - `NPerBlock = NRepeat * (N * n * NPerThread)`

### Visualization

<img src="https://user-images.githubusercontent.com/3454501/183738283-d0d09ec2-2e47-4f7a-ae8c-d24210bf8b06.png" width=75% height=75%>

- An arbitrary row:
  - Start with `tid / (threads * N)` tile
  - Within the tile, the thread index is `(tid % threads) / n`
  - Therefore, `row = tid / (threads * N) + (tid % threads) / n
- An arbitrary column:
  - Start with `tid / (threads % N)` tile
  - Within the tile, the thread index is `tid % n`  
  - Therefore, `column = (tid / threads) % N + (tid % n)`

The blockwise would loop through the M * N tiles in the following fashion:
```cpp
for (int a_elem = 0; a_elem < MRepeat * MPerThread; ++a_elem) {
  curRow = a_elem % MPerThread + MPerThread * (row + M * m * (a_elem / MPerThread));
}
for (int b_elem = 0; b_elem < NRepeat * NPerThread; ++b_elem) {
  curCol = b_elem % NPerThread + NPerThread * (column + N * n * (b_elem / NPerThread));
}
```

**Comment by krzysz00** [comment]
I've edited some of the words and code above, please check them

**Comment by jerryyin** [comment]
@krzysz00 Thanks, it definitely makes the document more readable.
