### ISSUE TITLE
[verification stall]

### ISSUE THREAD

**Issue by asleepzzz** [ROCm/rocMLIR#73]
we can reproduce issue with  
step1:
/usr/local/bin/cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS="mlir;lld"  -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="X86;AMDGPU" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DBUILD_SHARED_LIBS=ON -DLLVM_BUILD_LLVM_DYLIB=ON   -DMLIR_KEVIN_DRIVER_ENABLED=1  -DMLIR_MIOPEN_DRIVER_ENABLED=1 -DMLIR_ENABLE_SQLITE=1 -DMLIR_ROCM_RUNNER_ENABLED=1

step2:
cmake --build . --target check-mlir

step3:
./bin/mlir-miopen-driver -p -c -x2  -pv | ./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void

it will stall and do not show results

**Comment by whchung** [comment]
The ticket was ill-prepared. It doesn't show the good and bad commit.
