### ISSUE TITLE
Please add a tag for 5.4.1

### ISSUE THREAD

**Issue by Madouura** [ROCm/rocMLIR#843]
Hi, I am packaging this among other libraries for nixpkgs. Seen here: https://github.com/NixOS/nixpkgs/commit/b0bd0b41ae15fcdb4e31d2f790ebb82cc16dbd67
I'm not sure if there were any pertinent changes regarding this library for 5.3.1, but like the other ROCm libraries, I believe this should have such a tag.

**Comment by Madouura** [comment]
Thank you!

**Comment by Madouura** [comment]
Please add a tag for 5.4.1.
This is important for package managers, especially if the source changes (the hash changes).
While AFAIK as long as the major version is the same, everything should be compatible, this is not ideal.

**Comment by krzysz00** [comment]
We haven't made any 5.4.0 -> 5.4.1 changes (if we had, there'd've been an update to the commit in MIOpen). We should probably tag 5.4.1, but there's nothing about the ROCm release process that makes that needed for this repository, so we historically ... don't.

**Comment by jerryyin** [comment]
@Madouura FYI 5.4.1 tag created. Refer to here: https://github.com/ROCmSoftwarePlatform/rocMLIR/tags
