### ISSUE TITLE
document about your work

### ISSUE THREAD

**Issue by jianlongf** [ROCm/rocMLIR#88]
I am interesting in your work about MIOpen Dialect and I want to based it to develop my compiler. Where I should start. Have you own document about it. 
And i find there are only conv, gemm and other Gpu operation without MIOpen layer op. Will you plan to support it or generate it by MLIR?

**Comment by whchung** [comment]
@jianlongf Thanks for your interest. The project is not ready for production use so there is no documentation available for now. In a couple of months after we finish validation work we'll supply documentation.

The initial goal is to generate convolution GPU kernels. But with building blocks set forth in the dialect, other ops could be possible.

**Comment by jianlongf** [comment]
@whchung thanks. Look forward to your product.

**Comment by jianlongf** [comment]
@whchung Hi, I have another problem that I want to build tool mlir-rocm-runner created by you. But build error : explicit specialization of ‘field’ after instantiation in ./mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h. So can you give me some guide about it.

**Comment by whchung** [comment]
@jianlongf Please refer to:

https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/miopen-dialect/mlir/utils/jenkins/Jenkinsfile.downstream

on how we configure our builds and run tests.

**Comment by jianlongf** [comment]
> @jianlongf Please refer to:
> 
> https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/miopen-dialect/mlir/utils/jenkins/Jenkinsfile.downstream
> 
> on how we configure our builds and run tests.

I refer to this and build successfully. Thx

**Comment by jianlongf** [comment]
Sorry for bothering you again. Another problem I want to consult is about miopen runner. As far as I concern, the command as below can call convolution kernel in MIOpen. So I open up log libmiopen.so by 
‘’’
export MIOPEN_ENABLE_LOGGING=1
export MIOPEN_ENABLE_LOGGING_CMD=1
export MIOPEN_LOG_LEVEL=6
‘’’
But I can’t get any log. So How do you prove you call the miopen library in /opt/rocm/miopen/lib
‘’’
 ./mlir-miopen-driver -p -fil_layout=ckyx -in_layout=cnhw -out_layout=knhw -c --host ../../mlir/test/mlir-miopen-driver/conv2d_harness_ckyx_cnhw_knhw.mlir | ./mlir-rocm-runner ../../mlir/test/mlir-miopen-driver/conv2d_harness_ckyx_cnhw_knhw.mlir  --shared-libs=../lib/librocm-runtime-wrappers.so --shared-libs=../lib/libmlir_runner_utils.so --entry-point-result=void
‘’’

**Comment by whchung** [comment]
MLIR MIOpen dialect is different from MIOpen.

MLIR MIOpen dialect (this project) aims to use MLIR technology to produce convolution kernels on AMD GPU. It is merely a kernel generator. It does not depend on MIOpen.

MIOpen, on the other hand, provides many more features, including C/C++ APIs, kernel tuning, solvers written in different algorithms (direct, winograd, FFT, implicit GEMM) and different technologies (HIP, OpenCL, assembly, MLIR).

Therefore, you can see MIOpen as one of the client applications of MLIR MIOpen dialect. @jerryyin has been working on getting this integration done. It’s ongoing now and not finished yet.

**Comment by whchung** [comment]
As a corollary, MIOpenDriver in MIOpen has nothing to do with mlir-miopen-driver in MLIR MIOpen dialect right now.

This project would likely be renamed when it becomes more matured to avoid future confusions.

**Comment by jianlongf** [comment]
@whchung got it with many thanks.
