### ISSUE TITLE
Undefined soname for MLIR libraries

### ISSUE THREAD

**Issue by tpkessler** [ROCm/rocMLIR#927]
Hi! I'm packaging rocMLIR for Arch Linux. The installed libraries have a generic "VERSION" suffix that makes it impossible to automatically check for ABI changes in the package or packages that depend on it. The problem is that `add_mlir_library` calls `llvm_add_library` that uses `LLVM_VERSION_MAJOR` and `LLVM_VERSION_SUFFIX` to set the soversion via `set_target_properties`. The file that defines these variables (in the external llvm-project) is included after the mlir folder. Thus the LLVM version is undefined and cmake defaults to VERSION. A possible solution is to copy the definitions of LLVM_VERSION_* to mlir/CMakeLists.txt.

**Comment by krzysz00** [comment]
Hi! Just wanted to follow up on whether these need to be the same as the LLVM versiors or whether we should use, for example, the ROCm versions instead. (See my comments on your PR)

**Comment by tpkessler** [comment]
Hey! I'm not an AMD developer (the package effort for Arch Linux is community-driven), so I can't comment on that. Looking further into the issue I see that even now so name is set with the linked PR, the generated libraries still have the "VERSION" suffix. So the issue must lie deeper, but I'm unable to figure out where it comes from.

**Comment by krzysz00** [comment]
I am an AMD developer, and I'm trying to clarify what you need out of the sonames and their versions? That is, when should they change? When there's a change to our public-facing API? Every release?

**Comment by krzysz00** [comment]
(It's been long enough since I've poked at the loader that I don't quite remember how that all works)

**Comment by tpkessler** [comment]
> That is, when should they change?

When there's an API change that requires to recompile all packages that depend on rocMLIR.

**Comment by ppanchad-amd** [comment]
@tpkessler Can you please check if your issue is resolved in the latest ROCm 6.2? If so, please close the ticket. Thanks!
